version: "3.4"

x-project-name: &project-name ${POSTGRES_DB}
x-host: &host ${PUBLIC_IP}:8080
x-protocol: &protocol http
x-db-host: &db-host postgres
x-db-username: &db-username ${POSTGRES_USER}
x-db-password: &db-password ${POSTGRES_PASSWORD}
x-profiles: &profiles prod

services:

  postgres:
    image: postgres:14.8-alpine3.18
    container_name: sabacc_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: sabacc_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SERVER_HOST: *host
      SERVER_PROTOCOL: *protocol
      SPRING_PROFILES_ACTIVE: *profiles
      SPRING_DATASOURCE_USERNAME: *db-username
      SPRING_DATASOURCE_PASSWORD: *db-password
      SPRING_DATASOURCE_DATABASE_HOST: *db-host
      SPRING_DATASOURCE_DATABASE_PORT: 5432
      SPRING_DATASOURCE_DATABASE_NAME: *project-name
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      GRADLE_OPTS: "-DskipTests"
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    volumes:
      - ./backend/src:/app/src
      - ./backend/build.gradle:/app/build.gradle
      - ./backend/settings.gradle:/app/settings.gradle
      - ./backend/gradle:/app/gradle

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: sabacc_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}

