version: "3.4"

x-project-name:
  &project-name sabacc

x-host:
  &host 103.90.75.122:88
x-protocol:
  &protocol http

x-db-host:
  &db-host postgres
x-db-username:
  &db-username postgres
x-db-password:
  &db-password postgres

x-profiles:
#  &profiles prod
  &profiles dev  # ← Изменили на dev для разработки

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./grafana-data:/var/lib/grafana

  backend:
    image: ghcr.io/ap1kkk/sabacc/backend:latest
    build:
      context: backend
#      dockerfile: Dockerfile
      dockerfile: Dockerfile.dev  # ← Используем dev Dockerfile
    container_name: sabacc_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres


    environment:
      SERVER_HOST: *host
      SERVER_PROTOCOL: *protocol

      SPRING_PROFILES_ACTIVE: *profiles

      #     Database
      SPRING_DATASOURCE_USERNAME: *db-username
      SPRING_DATASOURCE_PASSWORD: *db-password
      SPRING_DATASOURCE_DATABASE_HOST: *db-host
      SPRING_DATASOURCE_DATABASE_PORT: 5432
      SPRING_DATASOURCE_DATABASE_NAME: *project-name
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"  # ← Включаем DevTools
      GRADLE_OPTS: "-DskipTests"
      SPRING_DOCKER_COMPOSE_ENABLED: "false"

    volumes:
      - ./backend/src:/app/src
      - ./backend/build.gradle:/app/build.gradle
      - ./backend/settings.gradle:/app/settings.gradle
      - ./backend/gradle:/app/gradle

  postgres:
    restart: always
    image: postgres:14.8-alpine3.18
    container_name: sabacc_postgres
    environment:
      POSTGRES_PASSWORD: *db-password
      POSTGRES_USER: *db-username
      POSTGRES_DB: *project-name
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    image: ghcr.io/ap1kkk/sabacc/frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile.dev  # ← Используем dev Dockerfile
#      dockerfile: Dockerfile

    container_name: sabacc_frontend
#    ports:
#      - "5173:5173"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/app  # ← Hot reload для фронтенда
      - /app/node_modules  # ← Исключаем node_modules из volume

    command: npm run dev -- --host 0.0.0.0

    environment:
      - CHOKIDAR_USEPOLLING=true  # ← Важно для Docker
      - VITE_API_URL=http://localhost:8080/api