version: "3.8"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: sabacc_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sabacc}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sabacc_backend
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_DATASOURCE_DATABASE_HOST: postgres
      SPRING_DATASOURCE_DATABASE_PORT: 5432
      SPRING_DATASOURCE_DATABASE_NAME: ${POSTGRES_DB:-sabacc}
      PUBLIC_IP: ${PUBLIC_IP}
      SERVER_HOST: 0.0.0.0
      SERVER_PROTOCOL: http
      CRON_USER_CLEANUP: ${CRON_USER_CLEANUP}
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: sabacc_frontend
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: sabacc_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
