server:
  host: "95.79.225.7"
  protocol: "http"

websocket:
  logging: true
  stomp:
    endpoint: "/ws"
    allowed-origin:                  # соответствует WebsocketConfigProperties.Stomp.allowedOrigin
      - "http://95.79.225.7"        # фронтенд продакшн
      - "http://localhost:5173"
      - "http://localhost"
    allowed-origin-patterns:
      - "*"                          # при необходимости wildcard
    sock-js-enabled: true
  game:
    endpoint: "/game"
    allowed-origin:
      - "http://95.79.225.7"
      - "http://localhost:5173"
      - "http://localhost"
    allowed-origin-patterns:
      - "*"
    sock-js-enabled: true
  broker:
    destination-prefixes:
      - "/topic"
      - "/queue"
      - "/input"
    application-destination-prefixes:
      - "/app"
    user-destination-prefixes: "/user"
