server:
  port: 8080
  host: 0.0.0.0
  protocol: http

spring:
  application:
    name: sabacc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_DATABASE_HOST:postgres}:5432/${SPRING_DATASOURCE_DATABASE_NAME:sabacc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-migration-naming: false
    out-of-order: true
    baseline-on-migrate: true


security:
  cors:
    allowed-origin:
      - http://localhost:5173
      - http://${PUBLIC_IP}      # <- добавляем публичный IP из .env
      - http://${PUBLIC_IP}:5173 # <- если фронт в dev на 5173
websocket:
  stomp:
    allowed-origin: http://${PUBLIC_IP}
  game:
    allowed-origin: http://${PUBLIC_IP}